package com.rodrigoloq.moviepedia.retrofit.entities

data class MovieDetailResponse(val adult: Boolean = false,
                               val backdrop_path: String = "",
                               val belongs_to_collection: BelongsToCollection = BelongsToCollection(),
                               val budget: Int = 0,
                               val genres: List<Genre> = listOf(),
                               val homepage: String = "",
                               val id: Int = 0,
                               val imdb_id: String = "",
                               val origin_country: List<String> = listOf(),
                               val original_language: String = "",
                               val original_title: String = "",
                               val overview: String = "",
                               val popularity: Float = 0f,
                               val poster_path: String = "",
                               val production_companies: List<ProductionCompanies> = listOf(),
                               val production_countries: List<ProductionCountries> = listOf(),
                               val release_date: String = "",
                               val revenue: Long = 0,
                               val runtime: Int = 0,
                               val spoken_languages: List<SpokenLanguages> = listOf(),
                               val status: String = "",
                               val tagline: String = "",
                               val title: String = "",
                               val video: Boolean = false,
                               val vote_average: Float = 0f,
                               val vote_count: Int = 1){
}
